name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Update packages
      run: bash ./.github/workflows/update.sh

    - name: Build application
      run: |
        /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -B $GITHUB_WORKSPACE/build
        cmake --build $GITHUB_WORKSPACE/build -j $(nproc)

    - name: Prepare artifact
      run: |
        mkdir --parents artifact/MiisendU-Wii-U
        mv --verbose build/MiisendU-Wii-U.rpx artifact/MiisendU-Wii-U/MiisendU-Wii-U.rpx
        mv --verbose build/MiisendU-Wii-U.wuhb artifact/MiisendU-Wii-U/MiisendU-Wii-U.wuhb
        cp --verbose meta/* artifact/MiisendU-Wii-U

    - uses: actions/upload-artifact@v4
      with:
        name: MiisendU-Wii-U
        path: artifact/
