name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v3

    - name: Update packages
      run: bash ./.github/workflows/update.sh

    - name: Build application
      run: make

    - name: Prepare artifact
      run: |
        mkdir --parents artifact/MiisendU-Wii-U
        mv --verbose MiisendU-Wii-U.rpx artifact/MiisendU-Wii-U/MiisendU-Wii-U.rpx
        cp --verbose meta/* artifact/MiisendU-Wii-U

    - uses: actions/upload-artifact@v3
      with:
        name: MiisendU-Wii-U
        path: artifact/

    - uses: actions/upload-artifact@v3
      with:
        name: MiisendU-Wii-U-WUHB
        path: "*.wuhb"
