name: Continuous Integration

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v2

    - name: Update packages
      run: bash ./.github/workflows/update.sh

    - name: Build application
      run: make

    - name: Move file
      run: mv UsendMii-Client.rpx meta/UsendMii_Client.rpx

    - uses: actions/upload-artifact@master
      with:
        name: UsendMii_Client
        path: meta/
